# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Scuzzy_config = debug

else ifeq ($(config),release)
  Scuzzy_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Scuzzy

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Scuzzy:
ifneq (,$(Scuzzy_config))
	@echo "==== Building Scuzzy ($(Scuzzy_config)) ===="
	@${MAKE} --no-print-directory -C Scuzzy -f Makefile config=$(Scuzzy_config)
endif

clean:
	@${MAKE} --no-print-directory -C Scuzzy -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Scuzzy"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"